const products = {
  imgPath: '/assets/shopImages/',
  productsItems: [
    {
      id: 1,
      name: 'Fresh Tote',
      describcion: '',
      date: '2022-04-15',
      colors: [
        {
          color: 'white',
          img: 'bag3white',
          price: 30,
          discount: 10,
          hex: '#FFFFFF',
          XS: 23,
          S: 41,
          M: 13,
          L: 9,
          XL: 36,
          XXL: 47,
        },
        {
          color: 'blue',
          img: 'bag3blue',
          price: 30,
          discount: 0,
          hex: '#0000FF',
          XS: 38,
          S: 25,
          M: 18,
          L: 11,
          XL: 50,
          XXL: 1,
        },
        {
          color: 'black',
          img: 'bag3black',
          price: 30,
          discount: 50,
          hex: '#000000',
          XS: 15,
          S: 28,
          M: 46,
          L: 7,
          XL: 30,
          XXL: 44,
        },
      ],
    },
    {
      id: 2,
      name: 'Fresh T First',
      describcion: '',
      date: '2023-02-12',
      colors: [
        {
          color: 'white',
          img: 't2white',
          price: 60,
          discount: 0,
          hex: '#FFFFFF',
          XS: 21,
          S: 49,
          M: 36,
          L: 22,
          XL: 18,
          XXL: 14,
        },
        {
          color: 'blue',
          img: 't2blue',
          price: 60,
          discount: 0,
          hex: '#0000FF',
          XS: 5,
          S: 47,
          M: 12,
          L: 4,
          XL: 50,
          XXL: 32,
        },
        {
          color: 'black',
          price: 60,
          discount: 0,
          img: 't2black',
          hex: '#000000',
          XS: 44,
          S: 10,
          M: 8,
          L: 15,
          XL: 29,
          XXL: 3,
        },
      ],
    },
    {
      id: 3,
      name: 'Fresh T Second',
      describcion: '',
      date: '2021-11-05',
      colors: [
        {
          color: 'white',
          img: 't3white',
          price: 60,
          discount: 0,
          hex: '#FFFFFF',
          XS: 6,
          S: 19,
          M: 44,
          L: 2,
          XL: 49,
          XXL: 25,
        },
        {
          color: 'blue',
          img: 't3blue',
          price: 60,
          discount: 0,
          hex: '#0000FF',
          XS: 34,
          S: 27,
          M: 40,
          L: 37,
          XL: 13,
          XXL: 9,
        },
        {
          color: 'black',
          img: 't3black',
          price: 60,
          discount: 0,
          hex: '#000000',
          XS: 39,
          S: 24,
          M: 41,
          L: 45,
          XL: 16,
          XXL: 7,
        },
      ],
    },
    {
      id: 4,
      name: 'Metz Collab Tote',
      describcion: '',
      date: '2022-09-23',
      colors: [
        {
          color: 'white',
          img: 'bag4white1',
          price: 30,
          discount: 0,
          hex: '#FFFFFF',
          XS: 14,
          S: 33,
          M: 30,
          L: 50,
          XL: 7,
          XXL: 26,
        },
        {
          color: 'white',
          img: 'bag4white2',
          price: 30,
          discount: 0,
          hex: '#FFFFFF',
          XS: 12,
          S: 9,
          M: 15,
          L: 48,
          XL: 19,
          XXL: 38,
        },
      ],
    },
    {
      id: 5,
      name: 'BMetz Collab T',
      describcion: '',
      date: '2023-03-19',
      colors: [
        {
          color: 'white',
          img: 't4white1',
          price: 60,
          discount: 0,
          hex: '#FFFFFF',
          XS: 24,
          S: 6,
          M: 50,
          L: 40,
          XL: 32,
          XXL: 10,
        },
        {
          color: 'white',
          img: 't4white2',
          price: 60,
          discount: 0,
          hex: '#FFFFFF',
          XS: 7,
          S: 18,
          M: 23,
          L: 5,
          XL: 41,
          XXL: 47,
        },
      ],
    },
    {
      id: 6,
      name: 'Base 01 Tote',
      describcion: '',
      date: '2021-05-08',
      colors: [
        {
          color: 'white',
          img: 'bag1white',
          price: 30,
          discount: 0,
          hex: '#FFFFFF',
          XS: 49,
          S: 8,
          M: 17,
          L: 4,
          XL: 25,
          XXL: 21,
        },
        {
          color: 'blue',
          img: 'bag1blue',
          price: 30,
          discount: 0,
          hex: '#0000FF',
          XS: 27,
          S: 1,
          M: 48,
          L: 12,
          XL: 33,
          XXL: 11,
        },
        {
          color: 'black',
          img: 'bag1black',
          price: 30,
          discount: 10,
          hex: '#000000',
          XS: 9,
          S: 22,
          M: 31,
          L: 46,
          XL: 29,
          XXL: 44,
        },
      ],
    },
    {
      id: 7,
      name: 'Base 02 Tote',
      describcion: '',
      date: '2023-07-07',
      colors: [
        {
          color: 'white',
          img: 'bag2white',
          price: 30,
          discount: 0,
          hex: '#FFFFFF',
          XS: 15,
          S: 40,
          M: 35,
          L: 13,
          XL: 6,
          XXL: 2,
        },
        {
          color: 'blue',
          img: 'bag2blue',
          price: 30,
          discount: 0,
          hex: '#0000FF',
          XS: 14,
          S: 28,
          M: 19,
          L: 49,
          XL: 8,
          XXL: 16,
        },
        {
          color: 'black',
          img: 'bag2black',
          price: 30,
          discount: 0,
          hex: '#000000',
          XS: 32,
          S: 45,
          M: 27,
          L: 38,
          XL: 10,
          XXL: 30,
        },
      ],
    },
    {
      id: 8,
      name: 'Base T',
      describcion: '',
      date: '2021-12-17',
      colors: [
        {
          color: 'white',
          img: 't1white',
          price: 60,
          discount: 0,
          hex: '#FFFFFF',
          XS: 46,
          S: 7,
          M: 3,
          L: 21,
          XL: 26,
          XXL: 48,
        },
        {
          color: 'blue',
          img: 't1blue',
          price: 60,
          discount: 0,
          hex: '#0000FF',
          XS: 29,
          S: 36,
          M: 11,
          L: 33,
          XL: 47,
          XXL: 24,
        },
        {
          color: 'black',
          price: 60,
          discount: 0,
          img: 't1black',
          hex: '#000000',
          XS: 20,
          S: 50,
          M: 10,
          L: 30,
          XL: 43,
          XXL: 16,
        },
      ],
    },
    {
      id: 9,
      name: 'Base 01 Swet',
      describcion: '',
      date: '2022-08-04',
      colors: [
        {
          color: 'white',
          img: 'swet1white',
          price: 90,
          discount: 0,
          hex: '#FFFFFF',
          XS: 25,
          S: 41,
          M: 22,
          L: 39,
          XL: 35,
          XXL: 12,
        },
        {
          color: 'blue',
          img: 'swet1blue',
          price: 90,
          discount: 0,
          hex: '#0000FF',
          XS: 33,
          S: 28,
          M: 3,
          L: 43,
          XL: 18,
          XXL: 5,
        },
        {
          color: 'black',
          price: 90,
          discount: 0,
          img: 'swet1black',
          hex: '#000000',
          XS: 47,
          S: 16,
          M: 37,
          L: 34,
          XL: 14,
          XXL: 23,
        },
        {
          color: 'gray',
          img: 'swet1gray',
          price: 90,
          discount: 0,
          hex: '#808080',
          XS: 9,
          S: 27,
          M: 44,
          L: 1,
          XL: 19,
          XXL: 29,
        },
      ],
    },
    {
      id: 10,
      name: 'Base 02 Swet',
      describcion: '',
      date: '2023-06-01',
      colors: [
        {
          color: 'white',
          img: 'swet2white',
          price: 90,
          discount: 0,
          hex: '#FFFFFF',
          XS: 22,
          S: 30,
          M: 16,
          L: 7,
          XL: 8,
          XXL: 46,
        },
        {
          color: 'blue',
          img: 'swet2blue',
          price: 90,
          discount: 0,
          hex: '#0000FF',
          XS: 43,
          S: 26,
          M: 24,
          L: 42,
          XL: 2,
          XXL: 17,
        },
        {
          color: 'black',
          price: 90,
          discount: 0,
          img: 'swet2black',
          hex: '#000000',
          XS: 13,
          S: 49,
          M: 19,
          L: 15,
          XL: 31,
          XXL: 32,
        },
        {
          color: 'gray',
          img: 'swet2gray',
          price: 90,
          discount: 0,
          hex: '#808080',
          XS: 34,
          S: 48,
          M: 38,
          L: 40,
          XL: 12,
          XXL: 14,
        },
      ],
    },
  ],
};

export default products;
